### ISSUE TITLE
ABI mismatch between transaction kernel API and Wasm Canonical ABI

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#102]
### Problem

The [transaction kernel](https://github.com/0xPolygonMiden/miden-base/tree/main/miden-lib/asm/miden/kernels/tx) and its user-facing API uses the ad-hoc ABI for function parameters and results. See its usage in the basic wallet contract at https://github.com/0xPolygonMiden/miden-base/blob/9f57fb2f088679a192e48f1f8ee83435e57bf24a/miden-lib/asm/miden/contracts/wallets/basic.masm#

The MASM code compiled from Rust (Wasm component model) uses the [Canonical ABI](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md) for function parameters and results. 

Since the user code in Rust needs to call the transaction kernel API, their ABIs must match.

### Solution

~Rewrite the transaction kernel API functions to use the Canonical ABI. 
Since there are Pioneers that are intended to write MASM code directly against the existing transaction kernel API, we might want to make it sooner rather than later to avoid the Pioneer code breakage.~

We can generate wrappers for transaction kernel API during the compilation that will convert between Canonical ABI and Miden ad-hoc ABI. For this, we need to finalize the high-level Miden SDK API first and check transaction kernel API functions for any obstacles that might interfere with automatic wrapper generation.

```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/compiler/issues/113
- [ ] https://github.com/0xPolygonMiden/compiler/issues/114
```

**Comment by bobbinth** [comment]
What would be a few examples of how we'd need to change kernel procedures to comply with the canonical ABI? For example, in the [accounts](https://github.com/0xPolygonMiden/miden-base/blob/9f57fb2f088679a192e48f1f8ee83435e57bf24a/miden-lib/asm/miden/account.masm) module.

**Comment by greenhat** [comment]
The most affecting changes will be due to the following Canonical ABI rules:
- Anything larger than 8 bytes (i64) is returned via a pointer passed as an argument;
- Parameters of complex types (think `Asset`) are encoded according to Canonical ABI lowering rules.

Let's look at the `account::add_asset`:

```masm
#! Add the specified asset to the vault.
#!
#! Panics:
#! - If the asset is not valid.
#! - If the total value of two fungible assets is greater than or equal to 2^63.
#! - If the vault already contains the same non-fungible asset.
#!
#! Stack: [ASSET]
#! Output: [ASSET']
#!
#! - ASSET' final asset in the account vault is defined as follows:
#!   - If ASSET is a non-fungible asset, then ASSET' is the same as ASSET.
#!   - If ASSET is a fungible asset, then ASSET' is the total fungible asset in the account vault
#!     after ASSET was added to it.
export.add_asset
    syscall.account_vault_add_asset
end
```

So far I designed the WIT type for `Asset` as follows(`variant asset`):

```wit
    type felt = u64;
    type word = tuple<felt, felt, felt, felt>;

    record fungible-asset {
        asset: account-id,
        amount: u64
    }

    type non-fungible-asset = word;

    variant asset {
        fungible(fungible-asset),
        non-fungible(non-fungible-asset),
    }

```
https://github.com/0xPolygonMiden/compiler/blob/9a0302a7bc54cdbd07de07355c11b939a50815ea/tests/rust-apps-wasm/sdk/sdk/wit/miden.wit#L88-L91

And a `add_asset` kernel transaction API as: 

```wit
    add-asset: func(asset: asset) -> asset;
```
https://github.com/0xPolygonMiden/compiler/blob/9a0302a7bc54cdbd07de07355c11b939a50815ea/tests/rust-apps-wasm/sdk/sdk/wit/miden.wit#L105

I'm using it in the basic wallet code as follows:

```rust
#![no_std]

cargo_component_bindings::generate!();

use bindings::exports::miden::basic_wallet::basic_wallet::{Asset, Guest, Recipient, Tag};
use bindings::miden::base::tx_kernel::{add_asset, create_note, remove_asset};

struct Component;

impl Guest for Component {
    fn receive_asset(asset: Asset) {
        add_asset(asset);
    }

    fn send_asset(asset: Asset, tag: Tag, recipient: Recipient) {
        let asset = remove_asset(asset);
        create_note(asset, tag, recipient);
    }
}
```
https://github.com/0xPolygonMiden/compiler/blob/9a0302a7bc54cdbd07de07355c11b939a50815ea/tests/rust-apps-wasm/sdk/basic-wallet/src/lib.rs#L1-L19

And here is how the `add_asset` is expected according to the Canonical ABI to pass the parameter and receive the result. Let's look at the generated bindings (`add_asset` is `wit_import`):
```rust
      #[allow(unused_unsafe, clippy::all)]
      /// Add the specified asset to the vault
      pub fn add_asset(asset: Asset,) -> Asset{
        
        #[allow(unused_imports)]
        use ::cargo_component_bindings::rt::{alloc, vec::Vec, string::String};
        unsafe {
          
          #[repr(align(8))]
          struct RetArea([u8; 40]);
          let mut ret_area = ::core::mem::MaybeUninit::<RetArea>::uninit();
          use super::super::super::miden::base::types::Asset as V2;
          let (result3_0,result3_1,result3_2,result3_3,result3_4,) = match asset {
            V2::Fungible(e) => {
              let super::super::super::miden::base::types::FungibleAsset{ asset:asset0, amount:amount0, } = e;
              
              (0i32, ::cargo_component_bindings::rt::as_i64(asset0), ::cargo_component_bindings::rt::as_i64(amount0), 0i64, 0i64)
            },
            V2::NonFungible(e) => {
              let (t1_0, t1_1, t1_2, t1_3, ) = e;
              
              (1i32, ::cargo_component_bindings::rt::as_i64(t1_0), ::cargo_component_bindings::rt::as_i64(t1_1), ::cargo_component_bindings::rt::as_i64(t1_2), ::cargo_component_bindings::rt::as_i64(t1_3))
            },
          };
          let ptr4 = ret_area.as_mut_ptr() as i32;
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "miden:base/tx-kernel@1.0.0")]
          extern "C" {
            #[link_name = "add-asset"]
            fn wit_import(_: i32, _: i64, _: i64, _: i64, _: i64, _: i32, );
          }
          
          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import(_: i32, _: i64, _: i64, _: i64, _: i64, _: i32, ){ unreachable!() }
          wit_import(result3_0, result3_1, result3_2, result3_3, result3_4, ptr4);
          let l5 = i32::from(*((ptr4 + 0) as *const u8));
          use super::super::super::miden::base::types::Asset as V12;
          let v12 = match l5 {
            0 => {
              let e12 = {
                let l6 = *((ptr4 + 8) as *const i64);
                let l7 = *((ptr4 + 16) as *const i64);
                
                super::super::super::miden::base::types::FungibleAsset{
                  asset: l6 as u64,
                  amount: l7 as u64,
                }
              };
              V12::Fungible(e12)
            }
            n => {
              debug_assert_eq!(n, 1, "invalid enum discriminant");
              let e12 = {
                let l8 = *((ptr4 + 8) as *const i64);
                let l9 = *((ptr4 + 16) as *const i64);
                let l10 = *((ptr4 + 24) as *const i64);
                let l11 = *((ptr4 + 32) as *const i64);
                
                (l8 as u64, l9 as u64, l10 as u64, l11 as u64)
              };
              V12::NonFungible(e12)
            }
          };
          v12
        }
      }
```
https://github.com/0xPolygonMiden/compiler/blob/9a0302a7bc54cdbd07de07355c11b939a50815ea/tests/integration/expected/sdk_basic_wallet/bindings/basic_wallet_bindings.rs#L152-L217

If you look at the kernel API `add_asset` call - `wit_import(result3_0, result3_1, result3_2, result3_3, result3_4, ptr4);`. It has the following parameters:
- `result3_0` - is a variant type `0` for `Fungible` and `1` for `NonFungible`;
- `result3_1` - `result3_4` - are encoded variant values; in case of `Fungible` it's `asset`,`amount`, 0, 0), in case of `NonFungible` it's `t1_0`, `t1_1`, `t1_2`, `t1_3` (the `word` type); See the Rust code above for lowering before the call;
- `ptr4` - is a pointer to the result area where the returned `asset` value must be written using the same encoding as above. See the Rust code above for lifting after the call.

**Comment by bobbinth** [comment]
> Anything larger than 8 bytes (i64) is returned via a pointer passed as an argument;

Hmm - I'm not sure this is a good idea. I believe we discussed previously that `word`s (i.e., 32 bytes) would be passed by value. This is very important as the alternative would be much less efficient. We may need to discuss how to bridge the gap here.

> So far I designed the WIT type for `Asset` as follows(`variant asset`):
> 
> ```wit
>     type felt = u64;
>     type word = tuple<felt, felt, felt, felt>;
> 
>     record fungible-asset {
>         asset: account-id,
>         amount: u64
>     }
> 
>     type non-fungible-asset = word;
> 
>     variant asset {
>         fungible(fungible-asset),
>         non-fungible(non-fungible-asset),
>     }
> ```

Let's discuss this as well as this is different from how we define assets in the kernel. Technically, the is really `Asset(Word)` - and I'm not quite sure what's the best way to express this in a higher-level language.
