### ISSUE TITLE
Low-level tx kernel API types in Miden SDK

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#113]
Introduce low-level (`core`?) types and functions so that their signatures will be close to the existing transaction kernel API.

Introduce the conversion functions between low-level and high-level types.

Native Miden VM `felt` support is extracted into #118

**Comment by greenhat** [comment]
@bitwalker 
I've found the interface remapping option in `wit-bindgen` but not anything related to a single type remapping. I believe we can make use of it with types that we want to remap put in the separate interface(s).

See the test for it at https://github.com/bytecodealliance/wit-bindgen/blob/442f0054fef4a7ff3c7fa59cbce7f9024569c5bc/crates/rust/tests/codegen.rs#L350-L403
and here is `Opts::with` at https://github.com/bytecodealliance/wit-bindgen/blob/442f0054fef4a7ff3c7fa59cbce7f9024569c5bc/crates/rust/src/lib.rs#L178-L180

To make it work in `cargo-component` we'd need to parse these mappings from Cargo.toml metadata. `cargo-component` builds and passes the `Opts` at https://github.com/bytecodealliance/cargo-component/blob/b34443033f067c3779519fd828c0886664e909fd/src/bindings.rs#L188-L203

I'll be happy to work on a PR to `cargo-component` implementing it. There is already an issue https://github.com/bytecodealliance/cargo-component/issues/225 for this feature created 7 hours ago (great timing!) by another `cargo-component` user. I can figure out if the maintainer is interested in this feature and start cracking. 

But before that, I'd like to experiment with implementing some methods for the existing types to see how we can propagate remapped interfaces implementation code through dependencies `sdk` -> `basic-wallet` -> `p2id-note`. Currently, each generates Rust bindings from the referenced WIT files for the same "SDK" types, and there are no crate level dependencies between them.

**Comment by greenhat** [comment]
> @bitwalker I've found the interface remapping option in `wit-bindgen` but not anything related to a single type remapping. I believe we can make use of it with types that we want to remap put in the separate interface(s).

I found that type and resource remapping are missing in `wit-bindgen` compared to wasmtime's `bindgen!`. See https://github.com/bytecodealliance/wit-bindgen/issues/825#issuecomment-1917541546
So they have to be implemented in `wit-bindgen` first before they can be used in `cargo-component`. It'll take more time, but I'll be happy to jump on it. Do you think type remapping is preferable to interface remapping in our case?

**Comment by bitwalker** [comment]
@greenhat Ah that's where I remember seeing, in wasmtime's `bindgen!` macro, nice find!

I think it's worth us porting over the type/interface remapping used in wasmtime's `bindgen!` (i.e. the `with` option). That'll be pretty critical for us, much more so than just being able to control which interfaces are generated (which might force us to do gross things like break up interfaces we might not otherwise, just so we can have more granular control over what gets emitted). Type remapping is super useful IMO, so worth doing.

**Comment by greenhat** [comment]
@bitwalker I've tried the `wit-bindgen`'s `with` option for interface remapping to get a picture of how Miden SDK users would use it in their projects (think wallets, notes, etc). 

On top of the existing direct importing of Miden SDK WIT file, they'd also need to specify a type remapping metadata (I assume a section in `Cargo.toml`) and include a Miden SDK crate with remapped types as a dependency. Although it looks like a lot of hoops to jump through, I hope we can streamline this DX in our cargo extension and package management tooling.

**Comment by greenhat** [comment]
> @greenhat Ah that's where I remember seeing, in wasmtime's `bindgen!` macro, nice find!
> 
> I think it's worth us porting over the type/interface remapping used in wasmtime's `bindgen!` (i.e. the `with` option). That'll be pretty critical for us, much more so than just being able to control which interfaces are generated (which might force us to do gross things like break up interfaces we might not otherwise, just so we can have more granular control over what gets emitted). Type remapping is super useful IMO, so worth doing.

I made #117 for this to get back to it later. I want to finish WIT low-level and high-level API (this task) and #114, keeping in mind that the type remapping will be there eventually.

**Comment by greenhat** [comment]
I extracted Miden VM native `felt` support in to the separate tracking issue - #118
