### ISSUE TITLE
MASM pseudo code for dealing procedure

### ISSUE THREAD

**Issue by nlok5923** [0xPolygonMiden/compiler#148]
Hi Guys!

Can you help me write MASM code for the below `dealing` procedure for a poker game.

### Pseudo code for the dealing procedure

Description: Given a deck of cards where the cards are already encrypted and shuffled using dealing procedure we need to distribute the card among regular update accounts.

For now let’s assume that the card is a struct and we need to deal cards among 4 regular updatable account

```
struct Card {
  cardType: enum,
  cardNumber: number,
  cardColor: enum
}

struct Deck {
 isShuffled: boolean,
 Cards[52; Card],
 isEncrypted: boolean
}
```

### Pseudo code for dealing

```
Game {
... // several other game procedures

accountId public players[4];
Deck public deck;
mapping(accountId => Card[2]) playerCards;

function dealCards() { 
    let _cardIndex = 0;
    for _, playerAccountId in players {
       for _ in 0..2 {
           playerCards[playerAccountId] = deck[_cardIndex];
           _cardIndex++;
       }
    }    
}

... // several other game procedures
}
```

**Comment by bitwalker** [comment]
Closing this as answered, but for future readers, issues like these are better asked in [0xPolygonMiden/examples](https://github.com/0xPolygonMiden/examples) (help with example code, or suggestions for new examples), [0xPolygonMiden/miden-vm](https://github.com/0xPolygonMiden/miden-vm) (questions or issues with the implementation of a specific procedure in Miden Assembly), or [0xPolygonMiden/miden-base](https://github.com/0xPolygonMiden/miden-base) (questions or issues with rollup-specific procedures and entities such as accounts). This repo is the best place for questions/issues related to compilation from Rust/Wasm to MASM specifically, and has fewer eyes on it than the other repos I mentioned.
