### ISSUE TITLE
Missing Miden VM ops counterparts in the IR, preventing their exposure to Rust via intrinsics

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#152]
While working on #151 I've noticed that there are some Miden VM operations that are not present in the IR. Which prevents us from exposing them to the user in Rust via intrinsic functions.

Here is a list of them:

### Field Operations

- ilog2
- assert_eqw
- eqw
- ext2*

see [Miden VM book](https://0xpolygonmiden.github.io/miden-vm/user_docs/assembly/field_operations.html )

### I/O

- adv* (advice_provider)

see [Miden VM book](https://0xpolygonmiden.github.io/miden-vm/user_docs/assembly/io_operations.html )

### Cryptographic operations

- hash;
- hperm;
- hmerge;
- mtree*;

see [Miden VM book](https://0xpolygonmiden.github.io/miden-vm/user_docs/assembly/cryptographic_operations.html )

### Events, Tracing

Already planned in https://github.com/0xPolygonMiden/compiler/issues/33 

- emit;
- trace;

see [Miden VM book](https://0xpolygonmiden.github.io/miden-vm/user_docs/assembly/events.html )

**Comment by bitwalker** [comment]
Yep, I've added all the missing instructions in my local branch that refactors to use the changes in 0xPolygonMiden/miden-vm#1277, so once that is merged all of these will be represented in the MASM IR, and the arithmetic ops are surfaced in the HIR instruction set. The remainder we will need to determine how we want to surface/represen, i.e. in some cases we may want to surface them more or less directly as an intrinsic, and in others we may want to provide higher-level HIR instructions that then lower to some sequence of MASM ops, as we do with various instructions already.

**Comment by bitwalker** [comment]
All of these instructions are now represented in the IR, although few of them are available via the HIR builders yet. I'm going to close this issue as completed, and let's open up new issues once we determine how we want to surface these in the frontend of the compiler.
