### ISSUE TITLE
Implement useful, but as of yet unsupported, Wasm instructions

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/compiler#19]
The following is a list of instructions we would like to add support for in the codegen backend when we get a chance. Unless explicitly called out, these instructions are exposed in the IR, and translated from Wasm already, but compilation will fail due to lack of support in the backend.

```[tasklist]
### Tasks
- [ ] `clz` (unsupported in both IR and codegen)
- [ ] `ctz` (unsupported in both IR and codegen)
- [x] `shr_s`
- [x] `gt_s`
- [x] `ge_s`
- [x] `lt_s`
- [x] `le_s`
- [x] `div_s`
- [x] `rem_s`
```

Assume that unless otherwise stated, all type variants of the above instructions are desired.

**Comment by greenhat** [comment]
I cannot edit the description. Translation for the following Wasm ops:

- `shr_s`
- `gt_s`
- `ge_s`
- `lt_s`
- `le_s`
- `div_s`
- `rem_s`

is implemented in https://github.com/0xPolygonMiden/miden-ir/pull/22/commits/0bd63606243d0c48bdbc19e60d272e06659169a1
