### ISSUE TITLE
`release-plz update` should bump minor and major version of the crates

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#295]

**Comment by greenhat** [comment]
@bitwalker I believe the reasons why only patch version was bumped are:
1. `release-plz` uses `next_version` to bump the version and according to the https://www.conventionalcommits.org/en/v1.0.0/#summary 
In their [docs](https://docs.rs/next_version/0.2.19/next_version/) they treat `feat:` as a minor version bump only when the major version is not zero. And since we have not used a breaking change [prefix](https://www.conventionalcommits.org/en/v1.0.0/#summary) in our commits, we are not bumping the major version either.
2. `release-plz` also uses `cargo-semver-checks` to check the semver violations and bump the versions accordingly. See the explanation at https://release-plz.ieni.dev/docs/semver-check
But since I have not installed `cargo-semver-checks` it was skipping this check. :facepalm:

So, as soon as we hit the `1.0.0`(major) version the feature commits will bump the minor version and the breaking change commits and/or `cargo-semver-checks` will bump the major version.

**Comment by bitwalker** [comment]
Makes sense, sounds like things are working as expected then for the time being. I think we can probably close this issue then!
