### ISSUE TITLE
Keep local Rust toolchain version in sync with CI automatically. 

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#45]
Set the Rust toolchain version via `rust-toolchain.toml` and use it in 'cargo make`. 
See details at https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by bitwalker** [comment]
I've added a `rust-toolchain.toml` file to the repo, and set it to the nightly toolchain until the `trait_upcasting` feature is stabilized in the next release, then we'll switch back to stable. In any case, it'll be easier to keep things in sync using that from now on.

Added in #50

**Comment by greenhat** [comment]
`cargo-make` on CI is still driven by `CARGO_MAKE_TOOLCHAIN` env var set in `ci.yml`. I guess removing the env var might be enough for `cargo-make` to follow the `rust-toolchain.toml`.

**Comment by greenhat** [comment]
Done in #91
