### ISSUE TITLE
Cargo extension for compiling Rust code to MASM

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#60]
In the first version of the extension, we will support only library targets because #59 is a blocker for app targets.

Commands:
* Create a new cargo project. Set `#no_std` required stuff in `lib.rs` (panic handler, etc.) and release profile options (size optimization, panic=abort, etc.)
* Compile the cargo project to MASM.

**Comment by bobbinth** [comment]
Should this extension go into a different repo? Maybe `miden-sdk` or something else?

**Comment by greenhat** [comment]
> Should this extension go into a different repo? Maybe `miden-sdk` or something else?

I expect it to be a thin wrapper on top of `midenc` code, so most of the new code and changes will end up in this repo anyway. I'd instead start it as a crate here to avoid unnecessary PRs. We can always extract it into a separate repo later.

**Comment by bobbinth** [comment]
I guess we can start here and then, if it becomes more signifiant, move it to another repo.

I do think we might expand the feature set quite a bit in the future. For example, this extension could handle things like ABI generation for Miden accounts.

**Comment by greenhat** [comment]
> I do think we might expand the feature set quite a bit in the future. For example, this extension could handle things like ABI generation for Miden accounts.

I expect the heavy lifting for ABI generation would be done by macros defined somewhere in Miden SDK. The extension would just call the `cargo run` on the user project, passing a special `feature` to trigger the file generation.

The cargo extension is just a naming convention for the "command" app binary. If we, for example, want to add `miden *` commands to the cargo, we need to publish a crate called `cargo-miden` that would compile an application target called `cargo-miden`. The `cargo install cargo-miden` would build our `cargo-miden` crate and put the binary into the cargo bin folder which is on the current user's PATH. When `cargo miden compile` is called, the `cargo-miden` binary is executed with `compile` argument. There is no access to the cargo internals or any rustc internals. Cargo extension is just a specially named binary that is executed by cargo.
