### ISSUE TITLE
Check for clippy warnings on CI

### ISSUE THREAD

**Issue by greenhat** [0xPolygonMiden/compiler#70]
It's hard to use a clippy when there are a lot (65) of warnings in the whole workspace. I suggest we add a CI job that will fail on clippy warnings. Although I find almost all of the warnings useful we can disable the ones we don't want.

**Comment by bitwalker** [comment]
All of the outstanding clippy warnings should be addressed now that #68 is merged. We just need to add a step to our build that checks for clippy warnings/errors and bails. I'd prefer to do that as a separate job though so it doesn't cause the main test job to fail early and can be handled as a separate step.
